//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_PhuCap
    {
        public int ID { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaPC { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhuCap PhuCap { get; set; }
    }
}
