//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TangCa
    {
        public int MaTC { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<double> SoGio { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaLoaiCa { get; set; }
    
        public virtual LoaiCa LoaiCa { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
